export const form = document.querySelector('form'),
    petname = document.querySelector('#pet-name'),
    ownername = document.querySelector("#owner-name"),
    phone = document.querySelector('#phone'),
    date = document.querySelector('#date'),
    hour = document.querySelector('#hour'),
    symptoms = document.querySelector('#symptoms'),
    appointmenttitle = document.querySelector('#appointment-title'),
    appointments = document.querySelector('#appointments');